# Generated by Django 5.1.3 on 2024-11-15 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="DetailWork",
            fields=[
                ("work_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("work_name", models.CharField(max_length=15)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_works",
                        to="sch_requests.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FamilySchedule",
            fields=[
                (
                    "fam_schedule_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("schedule_start_time", models.DateTimeField()),
                ("schedule_end_time", models.DateTimeField()),
                ("schedule_title", models.CharField(max_length=30)),
                (
                    "schedule_memo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_daily", models.BooleanField(default=False)),
                ("is_weekly", models.BooleanField(default=False)),
                ("is_monthly", models.BooleanField(default=False)),
                ("is_yearly", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_schedules",
                        to="sch_requests.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="요청 수락 여부"),
                ),
                (
                    "is_checked",
                    models.BooleanField(default=False, verbose_name="요청 확인 여부"),
                ),
                (
                    "fam_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sch_requests.familyschedule",
                    ),
                ),
                (
                    "sent_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snt_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trg_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
