# Generated by Django 4.2.16 on 2024-11-14 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('family_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fam_num', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyEmptyTime',
            fields=[
                ('family_empty_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('family_empty_date', models.DateField()),
                ('family_empty_min', models.PositiveIntegerField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.familyinfo')),
            ],
        ),
    ]
