# Generated by Django 4.2.16 on 2024-11-14 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_num', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyEmptyTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_empty_date', models.DateField()),
                ('family_empty_min', models.PositiveIntegerField()),
                ('family_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.familyinfo')),
            ],
        ),
    ]
