# Generated by Django 4.2.16 on 2024-11-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=50, verbose_name='제휴업체 이름')),
                ('place_link', models.URLField(max_length=500, verbose_name='제휴업체 링크')),
                ('place_img', models.ImageField(blank=True, null=True, upload_to='place_img%Y%m%d/', verbose_name='제휴업체 사진')),
                ('place_min_time', models.PositiveIntegerField(verbose_name='제휴업체 최소 이용시간(분)')),
            ],
        ),
    ]
