# Generated by Django 4.2.16 on 2024-11-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_img',
            field=models.ImageField(blank=True, null=True, upload_to='place_img/%Y%m%d/', verbose_name='제휴업체 사진'),
        ),
    ]
