# Generated by Django 5.1.3 on 2024-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
