# Generated by Django 5.1.3 on 2024-11-15 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyMemo",
            fields=[
                ("memo_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="가족 한마니 내용"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="작성일시"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalSchedule",
            fields=[
                (
                    "personal_schedule_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "schedule_title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="개인 스케줄 내용"
                    ),
                ),
                (
                    "schedule_start_time",
                    models.DateTimeField(verbose_name="개인 스케줄 시작 시간"),
                ),
                (
                    "schedule_end_time",
                    models.DateTimeField(verbose_name="개인 스케줄 종료 시간"),
                ),
                ("is_daily", models.BooleanField(default=False, verbose_name="데일리")),
                ("is_weekly", models.BooleanField(default=False, verbose_name="위클리")),
                ("is_monthly", models.BooleanField(default=False, verbose_name="먼슬리")),
                ("is_yearly", models.BooleanField(default=False, verbose_name="이얼리")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEmptyTime",
            fields=[
                (
                    "user_empty_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("user_empty_day", models.DateField(verbose_name="빈 날짜")),
                ("user_empty_start_time", models.TimeField(verbose_name="빈 시간 시작")),
                ("user_empty_end_time", models.TimeField(verbose_name="빈 시간 종료")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_empty_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
