# Generated by Django 5.1.3 on 2024-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymemo",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="작성일시"),
        ),
    ]
