# Generated by Django 5.1.3 on 2024-11-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personal", "0002_alter_familymemo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familymemo",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="작성일시"
            ),
        ),
    ]
